name: sacola_shared
description: Código compartilhado entre o app mobile (Flutter) e web (Jaspr)
version: 1.0.0

environment:
  sdk: ^3.9.0          # ← compatível com o teu mobile mais antigo e com o web

dependencies:
  riverpod: ^3.0.3
  uuid: ^4.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.4.13
  freezed: ^2.4.1
  json_serializable: ^6.8.0